import { Image } from "expo-image";
import { useRouter } from "expo-router";
import { useState } from "react";
import {
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import Animated, { FadeInDown, FadeInUp } from "react-native-reanimated";

import { Button } from "@/components/Button";
import { Screen } from "@/components/Screen";
import { TextField } from "@/components/TextField";
import { useAuth } from "@/services/auth";
import { haptic } from "@/services/haptics";
import { t } from "@/services/i18n";
import { isValidIsraeliId } from "@/services/auth/israeliId";
import { useUiStore } from "@/stores/uiStore";
import { useTheme } from "@/theme/ThemeProvider";

// Brand logo — same asset the web uses for its full wordmark + crest. We
// render it as the hero element on the login screen so the mobile app
// shares brand identity with autotradeil.com.
const BRAND_LOGO = require("../../assets/logo-full.png");

/**
 * Phone + ID login (mobile-only). Replaces the email/Google/Apple flow.
 *
 * Validation contract — local checks first to fail fast (saves an SMS
 * send against the rate limit budget), then the server re-validates and
 * verifies the phone+ID pair maps to one user row.
 *
 *   phone:     ^05\d{8}$  (Israeli mobile, 10 digits, no separators)
 *   id_number: ^\d{9}$ + Luhn-style checksum (see services/auth/israeliId.ts)
 *
 * On success → /verify-otp with `phone` and `idNumber` params. Both are
 * needed downstream because the verify call must replay them to prove
 * the same caller is the one who requested the code.
 */
function formatPhoneAsTyped(raw: string): string {
  const digits = raw.replace(/\D/g, "").slice(0, 10);
  if (digits.length <= 3) return digits;
  if (digits.length <= 6) return `${digits.slice(0, 3)}-${digits.slice(3)}`;
  return `${digits.slice(0, 3)}-${digits.slice(3, 6)}-${digits.slice(6)}`;
}

type FieldErrors = { phone?: string; idNumber?: string; form?: string };

export function PhoneLoginScreen() {
  const { requestPhoneOtp } = useAuth();
  const router = useRouter();
  const pushToast = useUiStore((s) => s.pushToast);
  const { colors, spacing, typography } = useTheme();

  const [phoneDisplay, setPhoneDisplay] = useState("");
  const [idNumber, setIdNumber] = useState("");
  const [errors, setErrors] = useState<FieldErrors>({});
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async () => {
    const phoneDigits = phoneDisplay.replace(/\D/g, "");
    const next: FieldErrors = {};

    if (!/^05\d{8}$/.test(phoneDigits)) {
      next.phone = t("auth.invalidPhone");
    }
    if (!/^\d{9}$/.test(idNumber)) {
      next.idNumber = t("auth.invalidID");
    } else if (!isValidIsraeliId(idNumber)) {
      next.idNumber = t("auth.invalidID");
    }

    if (next.phone || next.idNumber) {
      setErrors(next);
      return;
    }
    setErrors({});
    setSubmitting(true);
    try {
      await requestPhoneOtp(phoneDigits, idNumber);
      haptic.success();
      // Cast: typed routes file (.expo/types) is regenerated by `expo start`,
      // not by tsc — these strings resolve at runtime via expo-router's
      // file-based routing.
      router.push({
        pathname: "/verify-otp" as never,
        params: { phone: phoneDigits, idNumber },
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : t("errors.unknown");
      pushToast("error", msg);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Screen>
      <KeyboardAvoidingView
        style={{ flex: 1 }}
        behavior={Platform.OS === "ios" ? "padding" : undefined}
      >
        <ScrollView
          contentContainerStyle={{
            flexGrow: 1,
            paddingTop: 56,
            paddingBottom: spacing.xl,
          }}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          {/* Hero: logo near the top (~upper 1/4 of viewport) so the page
              reads as "brand → quick action" rather than the form floating
              in the middle. Title + subtitle sit tight below the logo. */}
          <Animated.View entering={FadeInUp.delay(80).springify()} style={styles.hero}>
            <Image
              source={BRAND_LOGO}
              style={styles.logo}
              contentFit="contain"
              transition={150}
              accessibilityLabel="AutoTradeIL"
            />
            <Text
              style={[
                typography.h2,
                {
                  // Extra room below the logo so the title + form group drops
                  // visibly without moving the logo itself.
                  color: colors.textPrimary,
                  marginTop: 56,
                  textAlign: "center",
                },
              ]}
            >
              {t("auth.secureLogin")}
            </Text>
          </Animated.View>

          {/* Form: stays a comfortable distance below the hero. 56px gap is
              the iOS-style "section break" that keeps the hero feeling
              prominent without orphaning the form lower in the viewport. */}
          <Animated.View
            entering={FadeInDown.delay(220).springify()}
            style={{ gap: spacing.lg, marginTop: 56 }}
          >
            <TextField
              label={t("auth.phone")}
              value={phoneDisplay}
              onChangeText={(v) => {
                setPhoneDisplay(formatPhoneAsTyped(v));
                if (errors.phone) setErrors((e) => ({ ...e, phone: undefined }));
              }}
              placeholder={t("auth.phonePlaceholder")}
              keyboardType="number-pad"
              autoComplete="tel"
              textContentType="telephoneNumber"
              maxLength={12}
              returnKeyType="next"
              error={errors.phone}
              editable={!submitting}
            />
            <TextField
              label={t("auth.idNumber")}
              value={idNumber}
              onChangeText={(v) => {
                setIdNumber(v.replace(/\D/g, "").slice(0, 9));
                if (errors.idNumber) setErrors((e) => ({ ...e, idNumber: undefined }));
              }}
              placeholder={t("auth.idPlaceholder")}
              keyboardType="number-pad"
              maxLength={9}
              returnKeyType="go"
              onSubmitEditing={handleSubmit}
              error={errors.idNumber}
              editable={!submitting}
            />
          </Animated.View>

          {/* Action: closer to the form than the hero — the user just
              filled the inputs and the eye should land on the CTA next. */}
          <Animated.View
            entering={FadeInDown.delay(320).springify()}
            style={{ gap: spacing.sm, marginTop: spacing.xl }}
          >
            <Button
              label={t("auth.sendSMS")}
              onPress={handleSubmit}
              loading={submitting}
              variant="primary"
            />
            <Text
              style={[
                typography.caption,
                { color: colors.textMuted, textAlign: "center" },
              ]}
            >
              {t("auth.smsWillBeSent")}
            </Text>
          </Animated.View>
        </ScrollView>
      </KeyboardAvoidingView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  hero: { alignItems: "center" },
  // Logo size tuned to ~30% of typical phone width; height follows the
  // wordmark's natural aspect (~3.1:1) so it never stretches.
  logo: { width: 240, height: 78 },
});
