import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import Animated, { FadeIn, FadeInDown } from "react-native-reanimated";

import { Button } from "@/components/Button";
import { PressableScale } from "@/components/PressableScale";
import { Screen } from "@/components/Screen";
import { useAuth } from "@/services/auth";
import {
  authenticateWithBiometric,
  detectBiometricKind,
  type BiometricKind,
} from "@/services/auth/biometric";
import { haptic } from "@/services/haptics";
import { t } from "@/services/i18n";
import { useUiStore } from "@/stores/uiStore";
import { useTheme } from "@/theme/ThemeProvider";

/**
 * One-time setup after first OTP login. User picks ONE of:
 *   1. Biometric (if hardware supports + user enrolled)
 *   2. PIN  (always available — taps through to /setup-pin)
 *   3. Skip (no lock; can opt-in later from settings)
 *
 * The "biometric" option is hidden if the device can't do it. The "skip"
 * route is allowed because Israeli dealer phones range widely and we
 * don't want to brick the app on devices without biometric / for users
 * who'll pick a PIN later.
 */
export function SetupBiometricScreen() {
  const router = useRouter();
  const pushToast = useUiStore((s) => s.pushToast);
  const { colors, radii, spacing, typography } = useTheme();
  const { setupBiometric, skipLockSetup } = useAuth();

  const [biometricKind, setBiometricKind] = useState<BiometricKind | null>(null);
  const [busy, setBusy] = useState<"bio" | "skip" | null>(null);

  useEffect(() => {
    detectBiometricKind().then(setBiometricKind);
  }, []);

  const onChooseBiometric = async () => {
    setBusy("bio");
    try {
      const ok = await authenticateWithBiometric(t("auth.bioPromptSetup"));
      if (!ok) {
        pushToast("error", t("errors.unknown"));
        return;
      }
      await setupBiometric();
      haptic.success();
      router.replace("/(tabs)/dashboard");
    } catch {
      pushToast("error", t("errors.unknown"));
    } finally {
      setBusy(null);
    }
  };

  const onChoosePin = () => {
    // Cast: typed-routes file (.expo/types) is regenerated by `expo start`,
    // not tsc; this resolves at runtime via expo-router file-based routing.
    router.push("/setup-pin" as never);
  };

  const onSkip = async () => {
    setBusy("skip");
    try {
      await skipLockSetup();
      router.replace("/(tabs)/dashboard");
    } finally {
      setBusy(null);
    }
  };

  const bioLabel =
    biometricKind === "face"
      ? t("auth.faceID")
      : biometricKind === "touch"
        ? t("auth.touchID")
        : null;
  const bioGlyph = biometricKind === "face" ? "😀" : "👆";

  return (
    <Screen>
      <View style={[styles.wrap, { padding: spacing.xl }]}>
        <Animated.View entering={FadeIn.duration(280)} style={styles.hero}>
          <Text style={styles.lockGlyph}>🔒</Text>
          <Text
            style={[
              typography.h1,
              { color: colors.textPrimary, textAlign: "center", marginTop: spacing.md },
            ]}
          >
            {t("auth.secureAccount")}
          </Text>
          <Text
            style={[
              typography.body,
              {
                color: colors.textSecondary,
                marginTop: spacing.md,
                textAlign: "center",
              },
            ]}
          >
            {t("auth.chooseAuthMethod")}
          </Text>
        </Animated.View>

        <View style={{ gap: spacing.md, marginTop: spacing.xxxl }}>
          {bioLabel ? (
            <Animated.View entering={FadeInDown.delay(120).springify()}>
              <PressableScale
                onPress={onChooseBiometric}
                disabled={busy !== null}
                hapticStyle="tap"
                style={{
                  ...styles.choice,
                  backgroundColor: colors.bgElevated,
                  borderColor: colors.border,
                  borderRadius: radii.lg,
                  padding: spacing.lg,
                }}
              >
                <Text style={styles.glyph}>{bioGlyph}</Text>
                <View style={{ flex: 1 }}>
                  <Text style={[typography.bodyBold, { color: colors.textPrimary }]}>
                    {bioLabel}
                  </Text>
                  <Text style={[typography.caption, { color: colors.textSecondary }]}>
                    {t("auth.fastAndSecure")}
                  </Text>
                </View>
              </PressableScale>
            </Animated.View>
          ) : null}

          <Animated.View entering={FadeInDown.delay(180).springify()}>
            <PressableScale
              onPress={onChoosePin}
              disabled={busy !== null}
              hapticStyle="tap"
              style={{
                ...styles.choice,
                backgroundColor: colors.bgElevated,
                borderColor: colors.border,
                borderRadius: radii.lg,
                padding: spacing.lg,
              }}
            >
              <Text style={styles.glyph}>🔢</Text>
              <View style={{ flex: 1 }}>
                <Text style={[typography.bodyBold, { color: colors.textPrimary }]}>
                  {t("auth.pinCode")}
                </Text>
                <Text style={[typography.caption, { color: colors.textSecondary }]}>
                  {t("auth.fourToSixDigits")}
                </Text>
              </View>
            </PressableScale>
          </Animated.View>
        </View>

        <View style={{ flex: 1 }} />

        <Animated.View entering={FadeInDown.delay(260).springify()}>
          <Button
            label={t("auth.skipForNow")}
            onPress={onSkip}
            loading={busy === "skip"}
            variant="ghost"
          />
        </Animated.View>
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  wrap: { flex: 1 },
  hero: { alignItems: "center", marginTop: 32 },
  lockGlyph: { fontSize: 56 },
  glyph: { fontSize: 32, marginEnd: 12 },
  choice: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
  },
});
