/**
 * Codegen entry point for `@autotradeil/shared-types`.
 *
 * What this does
 * --------------
 * Fetches FastAPI's OpenAPI document (default http://localhost:8000/openapi.json),
 * runs `openapi-typescript` against it, and writes the result to
 * `src/generated.ts`. A pristine copy of the schema is also written to
 * `openapi.snapshot.json` at the package root so CI can detect drift
 * between the API and the published types via a plain git diff.
 *
 * Two modes:
 *   default: overwrite src/generated.ts AND openapi.snapshot.json.
 *   --check: regenerate to a temp buffer and diff against the committed
 *            snapshot; exit non-zero on drift. Used by CI to fail builds
 *            when backend Pydantic models change without a corresponding
 *            shared-types regen + commit.
 *
 * Run with:
 *   pnpm --filter @autotradeil/shared-types generate
 *   pnpm --filter @autotradeil/shared-types generate:check
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(__dirname, "..");
const GENERATED_PATH = resolve(PACKAGE_ROOT, "src/generated.ts");
const SNAPSHOT_PATH = resolve(PACKAGE_ROOT, "openapi.snapshot.json");

const API_URL = process.env.OPENAPI_URL ?? "http://localhost:8000/openapi.json";
const CHECK_MODE = process.argv.includes("--check");

const HEADER = `/* eslint-disable */
/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Generated by \`pnpm --filter @autotradeil/shared-types generate\`
 * from the FastAPI OpenAPI document at ${API_URL}.
 *
 * If you need a friendly alias, add it to \`src/api.ts\` — never edit
 * this file. Drift between API and types is enforced by the
 * \`generate:check\` CI step.
 */
`;

async function fetchSchema(): Promise<unknown> {
  const res = await fetch(API_URL);
  if (!res.ok) {
    throw new Error(`Failed to fetch ${API_URL}: ${res.status} ${res.statusText}`);
  }
  return res.json();
}

async function renderTypes(schema: unknown): Promise<string> {
  const ast = await openapiTS(schema as Parameters<typeof openapiTS>[0]);
  return HEADER + astToString(ast);
}

async function readIfExists(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw err;
  }
}

async function main(): Promise<void> {
  const schema = await fetchSchema();
  const formattedSchema = JSON.stringify(schema, null, 2) + "\n";
  const generated = await renderTypes(schema);

  if (CHECK_MODE) {
    const existing = await readIfExists(SNAPSHOT_PATH);
    if (existing !== formattedSchema) {
      console.error(
        "✗ OpenAPI snapshot drift detected. Run `pnpm --filter @autotradeil/shared-types generate` and commit the result.",
      );
      process.exit(1);
    }
    const existingTypes = await readIfExists(GENERATED_PATH);
    if (existingTypes !== generated) {
      console.error(
        "✗ Generated types drift detected. Run `pnpm --filter @autotradeil/shared-types generate` and commit the result.",
      );
      process.exit(1);
    }
    console.log("✓ Shared types are in sync with the API.");
    return;
  }

  await mkdir(dirname(GENERATED_PATH), { recursive: true });
  await writeFile(GENERATED_PATH, generated, "utf8");
  await writeFile(SNAPSHOT_PATH, formattedSchema, "utf8");
  console.log(`✓ Wrote ${GENERATED_PATH}`);
  console.log(`✓ Wrote ${SNAPSHOT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
